version: "3"
services:
  web:
    build: .
    links:
      - "db:database"
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=database
      - DATABASE_PORT=27017
  db:
    image: mongo
    volumes:
      - data:/data/db
volumes:
  data: